### ISSUE TITLE
makeFeatureDbFromUCSC  not populating database correctly

### ISSUE THREAD

**Issue by lshep** [Bioconductor/GenomicFeatures#15]
See the details in the following support site post:
https://support.bioconductor.org/p/119066/

as James pointed out the `.adjustChromStarts` function reorders the columns. 
and as I pointed out the `insert_data_into_table` doesn't take into account a different ordering and populates the database incorrectly

**Comment by lshep** [comment]
Someone deleted the post -  which had all the details -  But I dug up a reply email from the support site with  James info:

The problem comes from .adjustChromStarts
```
Browse[2]> head(ucsc_table)
  bin chrom chromStart  chromEnd   name score expCount expNums expScores strand
1   3  chr1  184548974 184549885 SETDB1   436        1     589       212      *
2   4  chr1  226492354 226492784   CTCF   149        1      44       149      *
3   4  chr1  243269283 243269767 SETDB1   135        1     533       135      *
4   4  chr1  243269304 243269644   CHD2   239        1     479       239      *
5   4  chr1  243269306 243269746   CBX3   376        1     211       376      *
6   9  chr1    1048502   1049386   KAP1   380        1     508       380      *

debug: ucsc_table <- .adjustchromStarts(ucsc_table)

Browse[2]> head(ucsc_table)
  bin chrom  chromEnd   name score expCount expNums expScores strand chromStart
1   3  chr1 184549885 SETDB1   436        1     589       212      *  184548975
2   4  chr1 226492784   CTCF   149        1      44       149      *  226492355
3   4  chr1 243269767 SETDB1   135        1     533       135      *  243269284
4   4  chr1 243269644   CHD2   239        1     479       239      *  243269305
5   4  chr1 243269746   CBX3   376        1     211       376      *  243269307
6   9  chr1   1049386   KAP1   380        1     508       380      *    1048503
```
Which puts the chromStart column to the right. Then when the data are stuffed into the db, no accounting is made for the column ordering:
```
##Browse[3]> sql
 [1] "CREATE TABLE "                    "wgEncodeRegTfbsClusteredV3"      
 [3] " (\n"                             "  chrom TEXT NOT NULL,\n"        
 [5] "  strand TEXT NOT NULL,\n"        "  chromStart INTEGER NOT NULL,\n"
 [7] "  chromEnd INTEGER NOT NULL,\n"   "   bin  TEXT,\n"                 
 [9] "   name  TEXT,\n"                 "   score  TEXT,\n"               
[11] "   expCount  TEXT,\n"             "   expNums  TEXT,\n"             
[13] "   expScores  TEXT\n"             ")"         
```
## and then put into db using insert_data_into_table, which assumes (incorrectly) that the columns of
## the incoming data.frame match the columns of the just-created db
```
 insert_data_into_table <- function (conn, table, data) 
{
    stopifnot(is.list(data))
    placeholders <- pasterep.int("?", length(data)), collapse = ",")
    SQL <- sprintf("INSERT INTO %s VALUES (%s)", table, placeholders)
    params <- unname(as.list(data))
    params <- lapply(params, function(x) if (is.factor(x)) 
        as.character(x)
    else x)
    dbExecute(conn, SQL, params = params)
}
```
## which generates this SQL 
```
[1] "INSERT INTO wgEncodeRegTfbsClusteredV3 VALUES (?,?,?,?,?,?,?,?,?,?)"
```
There seems to just need to be a check for the ordering of the incoming data.frame to ensure that it matches the columns of the db table that it's getting put into.

**Comment by hamond** [comment]
hello! I'm Rodolfo. Somebody have banned me and delete my post. I don't know why! please help

**Comment by hamond** [comment]
Sesion info:
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

Required packages:
GenomicFeatures

Problem: 
In 2014 I wrote a code to obtain a genomic range object from a UCSC genome browser track and it worked fine. Nowadays, I can’t obtain the same result from the same code and function (features)
Code: 
`UCSCFeatureDbTableSchema(genome="hg19",
                         track="Txn Factor ChIP",
                         tablename="wgEncodeRegTfbsClusteredV3")
fdb<-makeFeatureDbFromUCSC(genome="hg19", ##### the download process could take a lot of time
                           track="Txn Factor ChIP",
                           tablename="wgEncodeRegTfbsClusteredV3")

TXF_2014<-features(fdb)
TXF_2014<-sort(TXF_2014)
show(TXF_2014)`

Output 2014:
`GRanges object with 4380444 ranges and 5 metadata columns:
         seqnames            ranges strand |         bin       score    expCount                     expNums                   expScores
            <Rle>         <IRanges>  <Rle> | <character> <character> <character>                 <character>                 <character>
  ZBTB33     chr1       10074-10329      * |         585         354           2                     204,246                     354,138
   CEBPB     chr1       10150-10413      * |         585         201           1                         343                         201
    CTCF     chr1       16111-16390      * |         585         227           7 213,612,621,627,628,631,662 110,139,171,209,227,200,170
    TAF1     chr1       29199-29688      * |         585         184           1                         157                         184
   GABPA     chr1       29276-29591      * |         585         198           1                         180                         198
     ...      ...               ...    ... .         ...         ...         ...                         ...                         ...
   NR3C1    chr22 51221928-51222237      * |         975         325           1                          58                         325
    PHF8    chr22 51221933-51222119      * |         975         256           1                          30                         256
   CREB1    chr22 51221944-51222223      * |         975         167           1                          47                         167
     SP4    chr22 51221978-51222258      * |         975         633           1                         155                         633
    SPI1    chr22 51223762-51224058      * |         975         213           2                     107,126                     213,161
  -------
  seqinfo: 24 sequences from hg19 genome; no seqlengths`
 

Output 2019 from the code (TXF_2014<-features(fdb)
Error in .normargSEW0(end, "end") : 
  'end' must be a numeric vector (or NULL)

**Comment by lshep** [comment]
@hamond  I'll look into the support site and getting you active again - that shouldn't have happened and I'm sorry

**Comment by lshep** [comment]
@hamond   I believe you should have access again.  please let me know if you do not

**Comment by hamond** [comment]
Hi! thanks a lot. It works know. I guess you already figured out my mail. Sorry for a delayed reply I have been in meetings during the last days. I'll keep you updated with my advances trying to solve the problem presented above.
Best regards

Rodolfo

**Comment by lshep** [comment]
Actually -   are you working with the release 3.8 or devel 3.9 version of Bioconductor?
