### ISSUE TITLE
'names' attribute [211] must be the same length as the vector [209]

### ISSUE THREAD

**Issue by jamesdalg** [Bioconductor/GenomicFeatures#3]
hg19.refseq.db<-GenomicFeatures::makeTxDbFromUCSC(genome="hg19", table="refGene")
Error in names(trackIds) <- sub("^ ", "", sapply(nodes, xmlValue)) : 
  'names' attribute [211] must be the same length as the vector [209]

Any idea on how to go about solving this? Is this a common issue? 
I'm running R 3.4.3 and tried reinstalling the package in addition to R, from scratch.  The issue still remains.

**Comment by hpages** [comment]
Hi @jamesdalg,

Thanks for the report. The error is actually happening in the rtracklayer package. It's easy to reproduce with:
```
library(rtracklayer)
session <- browserSession()
genome(session) <- "hg38"
track_names <- trackNames(session)
genome(session) <- "hg19"
track_names <- trackNames(session)
# Error in names(trackIds) <- sub("^ ", "", sapply(nodes, xmlValue)) : 
#   'names' attribute [210] must be the same length as the vector [208]
```
Seems like something has changed on the UCSC side that breaks `trackNames()` on hg19. Would you mind reporting this issue on the Bioconductor support site (https://support.bioconductor.org/) or here https://github.com/lawremi/rtracklayer ?

Thanks,
H.

**Comment by lawremi** [comment]
I fixed this in release and devel rtracklayer. Look for the upcoming versions.
