### ISSUE TITLE
Get gene_name column from GENCODE GTF?

### ISSUE THREAD

**Issue by Zepeng-Mu** [Bioconductor/GenomicFeatures#31]
Hi, I wonder whether it's possible to import columns other than "gene_id" from a GTF file to a TxDb?
To be specific, what I'm doing now is:
```r
gencode <- makeTxDbFromGFF("gencode.gtf", format = "gtf")
gene_gr <- genes(gencode, columns = "gene_id")
```
I want to do
```r
gene_gr <- genes(gencode, columns = c("gene_id", "gene_name"))
```

The `gene_name` entry in GENCODE GTF is basically the gene symbol. I want to have both information so I can work on ENSG ID and also to look at the gene symbol at the same time to get a better sense of the genes.

Right now it seems impossible to do this, or is there a way to do it?

Thanks in advance!

**Comment by lshep** [comment]
This would be better asked on the support site.  There is a lot more traffic and visibility on the support site and you may have better luck from the community that may have run into this situation before.   https://support.bioconductor.org/
