### ISSUE TITLE
Why 'downstream' is set to 200 by default in getPromoterSeq()

### ISSUE THREAD

**Issue by hpages** [Bioconductor/GenomicFeatures#35]
@paul-shannon Paul?

https://support.bioconductor.org/p/9140532/#9140650

Thanks,
H.

**Comment by hpages** [comment]
Also trying to ping you using your other GitHub account Paul @pshannon-bioc. Hope you don't mind :-)

**Comment by hpages** [comment]
Looks like Mchael Love gave a convincing answer to this on our support site: https://support.bioconductor.org/p/9140532/#9140650

**Comment by paul-shannon** [comment]
Hi Herve,

Sorry! I missed this discussion completely.

I see the issue is closed, and promoter as TSS-200bp seems to still stand.   

But if a universal constant is unsatisfactory, I think the Bioc annotatr package ("genomic regions in context”) might be more nuanced.

 - Paul

**Comment by hpages** [comment]
No worries. Thanks Paul!
