### ISSUE TITLE
makeTxDbFromGFF() how to handle entries lacking or duplicated "transcript_id" attribute  

### ISSUE THREAD

**Issue by madzayasodara** [Bioconductor/GenomicFeatures#36]
Hi, I'm getting these warnings when making a TxDb from a gff, which I rather avoid for my downstream analyses. 
How should I handle these instances, especially the ones that carry out as NA?
I checked and these entries are indeed there in the gff. I would rather save them if at all possible, but also ok with dropping the ones containing NA in the next step of my pipe `txdb.cds_by_transcript <- cdsBy(txdb, by="tx", use.names = TRUE) %>% drop_na(cds_name)` but `drop_na()` it's not applicable to that kind of object either.
```
> txdb <- makeTxDbFromGFF("BFgenomic.gff", format="gff")
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning messages:
1: In .extract_transcripts_from_GRanges(tx_IDX, gr, mcols0$type, mcols0$ID,  :
  some transcripts have no "transcript_id" attribute ==> their name ("tx_name" column in
  the TxDb object) was set to NA
2: In .extract_transcripts_from_GRanges(tx_IDX, gr, mcols0$type, mcols0$ID,  :
  the transcript names ("tx_name" column in the TxDb object) imported from the
  "transcript_id" attribute are not unique
```
Thank you,
-madza

**Comment by hpages** [comment]
Hi,

Note that `%>%` and `drop_na()` is not standard R syntax, but **tidyverse**-specific syntax. In general Bioconductor objects don't support the **tidyverse** syntax (there are a few exceptions). See [my answer](https://support.bioconductor.org/p/9140677/#9140683) on the Bioconductor support site for how to handle transcripts with no names, **using standard R syntax**. You'll need to get familiar with this syntax to make efficient use of Bioconductor.

Cheers,
H.

**Comment by madzayasodara** [comment]
Thank you!
