### ISSUE TITLE
makeTxDbFromEnsembl for Ensembl AnnotationHub objects?

### ISSUE THREAD

**Issue by mschubert** [Bioconductor/GenomicFeatures#49]
Hi,

I was trying to make txdb object from `AnnotationHub` Ensembl releases using the  `makeTxDbFromEnsembl` function, as this is what I thought this function did from its description line.

> The makeTxDbFromEnsembl function creates a TxDb object for a given organism by importing the genomic locations of its transcripts, exons, CDS, and genes from an Ensembl database.

```r
ens106 = AnnotationHub::AnnotationHub()[["AH100643"]]
txdb = GenomicFeatures::makeTxDbFromEnsembl(ens106)
# Error in .normarg_organism(organism) : 'organism' must be a single string
```

Reading the documentation more carefully (hence the edit), I realize that this function is not supposed to work on `AnnotationHub` objects.

However, would it make sense to provide this functionality?

<details>
<summary>sessionInfo</summary>

```
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

other attached packages:
 [1] ensembldb_2.20.1        AnnotationFilter_1.20.0
 [3] GenomicFeatures_1.48.1  AnnotationDbi_1.58.0
 [5] Biobase_2.56.0          GenomicRanges_1.48.0
 [7] GenomeInfoDb_1.32.2     IRanges_2.30.0
 [9] S4Vectors_0.34.0        BiocGenerics_0.42.0
```

</details>

**Comment by hpages** [comment]
Hi,

`AnnotationHub::AnnotationHub()[["AH100643"]]` is an EnsDb object:
```
ens106 <- AnnotationHub::AnnotationHub()[["AH100643"]]
ens106
# EnsDb for Ensembl:
# |Backend: SQLite
# |Db type: EnsDb
# |Type of Gene ID: Ensembl Gene ID
# |Supporting package: ensembldb
# |Db created by: ensembldb package from Bioconductor
# |script_version: 0.3.7
# |Creation time: Thu Apr 14 10:46:09 2022
# |ensembl_version: 106
# |ensembl_host: localhost
# |Organism: Homo sapiens
# |taxonomy_id: 9606
# |genome_build: GRCh38
# |DBSCHEMAVERSION: 2.2
# | No. of genes: 69340.
# | No. of transcripts: 269941.
# |Protein data available.
```
EnsDb objects are similar to TxDb objects i.e. you can immediately operate on them using the TxDb API (`transcriptLengths()`, `transcripts()`, `exons()`, `exonsBy()`, etc...). For example:
```
tx_lens <- transcriptLengths(ens106)
head(tx_lens)
#                           tx_id         tx_name         gene_id nexon tx_len
# ENST00000456328 ENST00000456328 ENST00000456328 ENSG00000223972     3   1657
# ENST00000450305 ENST00000450305 ENST00000450305 ENSG00000223972     6    632
# ENST00000488147 ENST00000488147 ENST00000488147 ENSG00000227232    11   1351
# ENST00000619216 ENST00000619216 ENST00000619216 ENSG00000278267     1     68
# ENST00000473358 ENST00000473358 ENST00000473358 ENSG00000243485     3    712
# ENST00000469289 ENST00000469289 ENST00000469289 ENSG00000243485     2    535
```

I'm not sure why you want to call `makeTxDbFromEnsembl()` on this EnsDb object? What are you trying to achieve? `makeTxDbFromEnsembl()` was never meant to be called on an EnsDb object. You seem to misunderstand the purpose of this function.

Please note that this type of question are better asked on [our support site](https://support.bioconductor.org/).
 
Cheers,
H.
