### ISSUE TITLE
Add 'genome' argument to makeTxDbFromGFF()

### ISSUE THREAD

**Issue by hpages** [Bioconductor/GenomicFeatures#55]
### Edit: All `makeTxDb*()` functions have moved to the new **txdbmaker** package. So I re-created this issue [there](https://github.com/Bioconductor/txdbmaker/issues/2) and I'm closing this one.

Right now (as of **GenomicFeatures** 1.51.4) `makeTxDbFromGFF()` produces a TxDb object that has an unspecified genome by default. To change this, one needs to explicitely set the genome on the TxDb object returned by `makeTxDbFromGFF()`, e.g. with `genome(txdb) <- "T2T-CHM13v2.0"` (it's important to use the official name of the assembly otherwise the `seqlevelsStyle()` setter won't be able to switch the sequence naming style to UCSC or RefSeq). Alternatively one can specify the genome at creation time with `makeTxDbFromGFF(..., metadata=data.frame(name="Genome", value="T2T-CHM13v2.0"))` but this is admitedly poorly documented and not very convenient.

So let's add a `genome` argument to `makeTxDbFromGFF()`.

**Comment by PanZiwei** [comment]
Hi,
I am interested to use [genomic annotation for T2T](https://github.com/marbl/CHM13#gene-annotation). Does Genomicfeatures support the T2T loading? If so, can you provde more hints on that? 
Thank you!
```
> makeTxDbFromGFF(..., metadata=data.frame(name="Genome", value="T2T-CHM13v2.0"))
Error: '...' used in an incorrect context
```

**Comment by hpages** [comment]
Your question is barely related to this issue. I opened a separate issue where I answer your question. See issue #65. Please use that other issue for any follow-up. Thanks!

H.

**Comment by hpages** [comment]
All `makeTxDb*()` functions have moved to the new **txdbmaker** package. So I re-created this issue [there](https://github.com/Bioconductor/txdbmaker/issues/2) and I'm closing this one.
