### ISSUE TITLE
Installation requires vctrs (≥ 0.6.0)

### ISSUE THREAD

**Issue by amitfrishberg** [Bioconductor/GenomicFeatures#64]
Hey,
I install this package as part of a package that I'm developing.
Until recently, this was not an issue.
However, in the last few days, I encounter errors due to vctrs (≥ 0.6.0) (see attached screenshot).
This was a surprise to me since your package does not require vctrs directly. I looked for the actual problem and I think it rises from the installation of dplyr (ver. 1.1.3). Older version did not require vctrs (≥ 0.6.0) so I didn't have this issue. I still don't understand why dplyr (ver. 1.1.3) is even required since you don't mention it in the dependencies.

Please help me figuring this out.
Thanks

![genomicFeaturesBug](https://github.com/Bioconductor/GenomicFeatures/assets/107349233/b799d167-c170-42f6-a96e-a68029279421)

**Comment by mtmorgan** [comment]
I used BiocPkgTools and igraph

```
df = BiocPkgTools::buildPkgDependencyDataFrame("strong", version = "3.18", repo = c("BioCsoft", "CRAN"))
ig = BiocPkgTools::buildPkgDependencyIgraph(df)
igraph::all_simple_paths(ig, "GenomicFeatures", "vctrs")
```
leading to
```
[[1]]
+ 5/20761 vertices, named, from f5e2abd:
[1] GenomicFeatures AnnotationDbi   RSQLite         blob
[5] vctrs

[[2]]
+ 6/20761 vertices, named, from f5e2abd:
[1] GenomicFeatures biomaRt         AnnotationDbi   RSQLite
[5] blob            vctrs
...
[[34]]
+ 4/20761 vertices, named, from f5e2abd:
[1] GenomicFeatures RSQLite         blob            vctrs
```
So AnnotationDbi, biomaRt (through several paths), and RSQLite all induce a dependency on vctrs.

Maybe you want to make sure that you update all packages, e.g.,  in a new session`BiocManager::install(ask = FALSE)` ? (this could be disruptive of your work if things go wrong with an installation).

**Comment by amitfrishberg** [comment]
I was able to solve it by removing ensembledb from my package and therefore not installing this package. 
I used your script and looked within the other packages that I import and didn't find what was the issue. 
The only package I could find is "BiocFileCache" but it doesn't require the latest version of vctrs, dplyr or dbplyr so I don't know how to explain that.

**Comment by mtmorgan** [comment]
Generally `BiocManager::install()` or `install.packages()` will install the most recent version of a package. [dplyr][] imports
`vctrs (>= 0.6.0)` so if a package depends or imports dplyr, then it will insist on vctrs >- 0.6.0. BiocFileCache depends on dplyr, so requires vctrs >= 0.6.0.

I'm not really understanding why you do not just update (`BiocManager::install("vctrs")`) vctrs ? From it's [CRAN page][vctrs] the most recent version is 0.6.3, and it is available on all platforms.

[dplyr]: https://cran.r-project.org/package=dplyr
[vctrs]: https://cran.r-project.org/package=vctrs

**Comment by amitfrishberg** [comment]
You are right. It is the best solution but I had some issues with this upgrade in our systems.
Anyway, the issue is solved and it appears not to be a GenomicFeatures issue so you can close the issue. Thank you for your help :)
