### ISSUE TITLE
GenomicFeatures:::load_package_gracefully apparently fails on BBS

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/GenomicFeatures#67]
Hi,

I got several build warnings on BBS with Bioc 3.19 during testing, which all look kind of the same:

From [RNAmodR](https://master.bioconductor.org/checkResults/3.19/bioc-LATEST/RNAmodR.ML/nebbiolo1-checksrc.html) package
```
Backtrace
      ▆
   1. └─RNAmodR::End5SequenceData(files, annotation = annotation, sequences = sequences) at test-0SequenceData.R:37:3
   2.   └─RNAmodR:::.new_SequenceData(...)
   3.     └─RNAmodR:::.norm_annotation(annotation, className)
   4.       └─GenomicFeatures::makeTxDbFromGFF(annotation)
   5.         └─GenomicFeatures:::call_fun_in_txdbmaker("makeTxDbFromGFF", ...)
   6.           └─GenomicFeatures:::load_package_gracefully(...)`
```

From [RNAmodR.ML](https://master.bioconductor.org/checkResults/3.19/bioc-LATEST/RNAmodR.ML/nebbiolo1-checksrc.html) package
```
Last 13 lines of output:
    3. │   ├─testthat (local) .capture(...)
    4. │   │ └─base::withCallingHandlers(...)
    5. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
    6. └─RNAmodR.ML (local) ModMLExample(files, annotation, sequences)
    7.   ├─RNAmodR:::Modifier(...) at test-RNAmodR.ML.R:16:5
    8.   └─RNAmodR:::Modifier(...)
    9.     └─RNAmodR:::.new_ModFromCharacter(...)
   10.       └─RNAmodR:::.norm_annotation(annotation, className)
   11.         └─GenomicFeatures::makeTxDbFromGFF(annotation)
   12.           └─GenomicFeatures:::call_fun_in_txdbmaker("makeTxDbFromGFF", ...)
   13.             └─GenomicFeatures:::load_package_gracefully(...)
```

I see that there are some recent changes from last week. I looked at changes and it seems that there is a new packlage 'txdbmaker' with a redirection to functions from that package.

@hpages Should I fix it in those packages or is this something you would like to address?
Thanks for any advice on how to fix this issue long term best.

Felix

edit: It might be a linux specific issue and/or timing related. Any advice would be much appreciated.

**Comment by hpages** [comment]
Looks like you already made changes to **RNAmodR** so let's wait until the next build report and see how that goes.

**Comment by hpages** [comment]
Things look good today for **RNAmodR** and its revdeps: https://bioconductor.org/checkResults/3.19/bioc-LATEST/RNAmodR/
